Add gltf loader types
three-types/three-ts-types pull request #143
Opened 2021-10-20 07:48 UTC by robertlong

### Why

This PR adds types to `GLTFParser` and `GLTFLoaderPlugin` which makes it easier to author new GLTFLoader plugins in typescript.

### What

This PR includes additional type definitions for the [GLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js) file.

I added types for properties to the `GLTFParser` such as `options` which is useful for accessing the `options.path` variable to determine the base path to use in a plugin. Or the `textureLoader` which is useful when you want to reuse the existing texture loader.

I also added the `createNodeMesh` hook to the `GLTFLoaderPlugin` which is used to create different mesh objects.

### Checklist

-   [x] Added myself to contributors table
-   [x] Ready to be merged

2021-10-20 07:51 UTC, joshuaellis requested changes
Two discussion points, also if you could reference the source of these changes (a link to the file in the three repo) that would be super helpful for us ⭐

2021-10-20 07:51 UTC, joshuaellis commented on types/three/examples/jsm/loaders/GLTFLoader.d.ts
> +        meshoptDecoder: /* MeshoptDecoder */ any;
could you explain why this is `any`?

2021-10-20 07:51 UTC, joshuaellis commented on types/three/examples/jsm/loaders/GLTFLoader.d.ts
> +    extensions: { [name: string]: any };
could you explain why this is `any`?

2021-10-21 06:46 UTC, robertlong commented on types/three/examples/jsm/loaders/GLTFLoader.d.ts
> +        meshoptDecoder: /* MeshoptDecoder */ any;
Currently there is no MeshoptDecoder type definitions and the [setMeshoptDecoder](https://github.com/three-types/three-ts-types/blob/master/types/three/examples/jsm/loaders/GLTFLoader.d.ts#L56) method already takes an any value so I stuck with that convention.

2021-10-21 06:50 UTC, robertlong commented on types/three/examples/jsm/loaders/GLTFLoader.d.ts
> +    extensions: { [name: string]: any };
The extensions object currently holds [booleans for the new plugins](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L335) and [various extension objects for the older extensions](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L349). In plugins you likely want to check for the existence of a given extension. Typing all the older extensions would likely be a waste of time because they are deprecated and likely to be ported to the newer plugin api soon enough.

2021-10-21 06:51 UTC, robertlong commented
Hopefully those comments and the link in the description should help. Let me know if there's anything else.

2021-11-07 09:42 UTC, joshuaellis commented on types/three/examples/jsm/loaders/GLTFLoader.d.ts
> +        meshoptDecoder: /* MeshoptDecoder */ any;
Makes sense with me!

2021-11-07 09:43 UTC, joshuaellis approved these changes

2021-11-07 09:44 UTC, merged