Fix Matrix3/4 `makeTranslation` types
three-types/three-ts-types pull request #481
Opened 2023-06-27 03:56 UTC by puxiao

https://threejs.org/docs/index.html#api/en/math/Matrix4.makeTranslation

```
makeTranslation( x, y, z ) {

		if ( x.isVector3 ) {

			this.set(
				1, 0, 0, x.x,
				0, 1, 0, x.y,
				0, 0, 1, x.z,
				0, 0, 0, 1

			);

		} else { 
			...
		}
}
```

2023-06-29 12:35 UTC, Methuselah96 requested changes
Thanks for the PR!

2023-06-29 12:35 UTC, Methuselah96 commented on types/three/src/math/Matrix3.d.ts
>      makeTranslation(x: number, y: number): Matrix3;
Can you make the return type `this` for both methods?

2023-06-29 12:35 UTC, Methuselah96 commented on types/three/src/math/Matrix4.d.ts
>      makeTranslation(x: number, y: number, z: number): Matrix4;
Can you make the return type `this` for both methods?

2023-06-29 13:31 UTC, Methuselah96 commented
I also just realized this is part of the r153 so the base branch should be `dev` instead of `master`. If you can't get around to these changes within the next few days, I can update the PR myself.

2023-06-30 01:05 UTC, closed without merging

2023-06-30 01:17 UTC, puxiao commented
Sorry, i resubmitted.
https://github.com/three-types/three-ts-types/pull/488

2023-06-30 01:20 UTC, Methuselah96 commented
No problem, thanks!