feat (Nodes): Improve NodeElements + tangential changes
three-types/three-ts-types pull request #734
Opened 2023-12-26 03:39 UTC by 0b5vr

@Methuselah96 I'm sorry if these changes overlap with what you are currently working on. 😓

### What

Improve NodeElements interface.

Search the whole three.js project by `addNodeElement(` to validate these changes.

- Nodes I added:
  - `CubeTextureNode.d.ts`: `cubeTexture`
  - `TextureNode.d.ts`: `texture`
  - `FunctionCallNode.d.ts`: `call`
  - `AssignNode.d.ts`: `assign`
  - `BypassNode.d.ts`: `bypass`
  - `CacheNode.d.ts`: `cache`, `globalCache`
  - `ContextNode.d.ts`: `context`, `label`
  - `VaryingNode.d.ts`: `varying`
  - `ColorSpaceNode.d.ts`: `linearTosRGB`, `sRGBToLinear`, `linearToColorSpace`, `colorSpaceToLinear`
  - `NormalMapNode.d.ts`: `normalMap`
  - `ViewportSharedTextureNode.d.ts`: `viewportSharedTexture`
  - `ViewportTextureNode.d.ts`: `viewportTexture`, `viewportMipTexture`
  - `FogExp2Node.d.ts`: `densityFog`
  - `FogNode.d.ts`: `fog`
  - `FogRangeNode.d.ts`: `rangeFog`
  - `ComputeNode.d.ts`: `compute`
  - `LightingContextNode.d.ts`: `lightingContext`
  - `CheckerNode.d.ts`: `checker`
  - `ShaderNode.d.ts`: `color`, `float`, `int`, ..., `bmat4`, `string`, `arrayBuffer`, `element`, `convert`
  - `RotateUVNode.d.ts`: `rotateUV`
  - `TriplanarTexturesNode.d.ts`: `triplanarTexture`
- Nodes I skipped: `toAttribute`, `textureSize`, `scriptable`, `scriptableValue`, `bumpMap`, `gaussianBlur`, `viewportDepthTexture`, `hash`, `discard`, `loop`, `directionToColor`, `colorToDirection`
- defined `globalCache`, a variant of CacheNode without cache scope
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/core/CacheNode.js#L44
- defined `label`, a variant of ContextNode that sets a label
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/core/ContextNode.js#L56
- `label` on `VarNode.d.ts` is removed instead
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/core/VarNode.js
- `colorSpace` has been removed, added `linearTosRGB`, `sRGBToLinear`, `linearToColorSpace`, `colorSpaceToLinear` instead
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/display/ColorSpaceNode.js#L97-L101
- `assign` has been moved from `OperatorNode` to `AssignNode` (new in this repo)
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/math/OperatorNode.js
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/core/AssignNode.js
- Add `string` and `arrayBuffer` to `ShaderNode.d.ts`
  - See: https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/shadernode/ShaderNode.js#L587-L588

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

2024-01-10 15:04 UTC, Methuselah96 requested changes
Thanks for working on this!

2024-01-10 15:04 UTC, Methuselah96 commented on types/three/examples/jsm/nodes/Nodes.d.ts
> +export { default as CacheNode, cache, globalCache } from './core/CacheNode.js';
I don't see `globalCache` being exported here in the source.

2024-01-10 15:04 UTC, Methuselah96 commented on types/three/examples/jsm/nodes/Nodes.d.ts
> +} from './display/ColorSpaceNode.js';
nit: I like to keep the order of the exports the same as in the source and type exports at the end to make it easy to verify the exports match the source.

```suggestion
export {
    default as ColorSpaceNode,
    linearToColorSpace,
    colorSpaceToLinear,
    linearTosRGB,
    sRGBToLinear,
    ColorSpaceNodeMethod,
} from './display/ColorSpaceNode.js';
```

2024-01-10 15:04 UTC, Methuselah96 commented on types/three/examples/jsm/nodes/core/AssignNode.d.ts
> +export const assign: (targetNode: Node, sourceNode: Node) => ShaderNodeObject<AssignNode>;
I think `nodeProxy` allows the arguments to be `NodeRepresentation`s that gets converted to `Node`s through the proxy implementation.

```suggestion
export const assign: (targetNode: NodeRepresentation, sourceNode: NodeRepresentation) => ShaderNodeObject<AssignNode>;
```

2024-01-10 15:04 UTC, Methuselah96 commented on types/three/examples/jsm/nodes/display/ColorSpaceNode.d.ts
> +export const colorSpaceToLinear: (node: NodeRepresentation, encoding: ColorSpace) => ShaderNodeObject<ColorSpaceNode>;
```suggestion
export const linearToColorSpace: (node: NodeRepresentation, colorSpace: ColorSpace) => ShaderNodeObject<ColorSpaceNode>;
export const colorSpaceToLinear: (node: NodeRepresentation, colorSpace: ColorSpace) => ShaderNodeObject<ColorSpaceNode>;
```

2024-01-11 04:32 UTC, 0b5vr commented on types/three/examples/jsm/nodes/Nodes.d.ts
> +export { default as CacheNode, cache, globalCache } from './core/CacheNode.js';
ah, it's exported from `nodes/core/CacheNode.js` but not exported from `nodes/Nodes`. Thanks.

```suggestion
export { default as CacheNode, cache } from './core/CacheNode.js';
```

2024-01-11 04:42 UTC, 0b5vr commented on types/three/examples/jsm/nodes/Nodes.d.ts
> +} from './display/ColorSpaceNode.js';
Agreed!

2024-01-11 05:02 UTC, 0b5vr commented on types/three/examples/jsm/nodes/core/AssignNode.d.ts
> +export const assign: (targetNode: Node, sourceNode: Node) => ShaderNodeObject<AssignNode>;
Ah, that's how `nodeProxy` works. thank you!

2024-01-11 05:03 UTC, 0b5vr commented on types/three/examples/jsm/nodes/display/ColorSpaceNode.d.ts
> +export const colorSpaceToLinear: (node: NodeRepresentation, encoding: ColorSpace) => ShaderNodeObject<ColorSpaceNode>;
True.

2024-01-11 05:05 UTC, 0b5vr commented
@Methuselah96 Thank you for the review! Resolved all the conversations.

2024-01-11 14:27 UTC, Methuselah96 approved these changes

2024-01-11 14:27 UTC, merged